[
	{
		"name":	"工作流基础数据",
		"data":[{
			"tableName": "FORM_TASK",
			"tableNameCN": "流程业务明细",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": ""
		},{
			"tableName": "FORM_TASKMAIN",
			"tableNameCN": "流程业务主表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": ""
		}]
	},
	{
		"name":	"数据集基础数据",
		"data":[{
			"tableName": "SYS_DATA_EXPORT",
			"tableNameCN": "SYS_DATA_EXPORT",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1531696400"
		}, {
			"tableName": "SYS_DATA_FIELD",
			"tableNameCN": "SYS_DATA_FIELD",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "806421392"
		}, {
			"tableName": "SYS_DATA_FILE",
			"tableNameCN": "SYS_DATA_FILE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1386367949"
		}, {
			"tableName": "SYS_DATA_FROM",
			"tableNameCN": "SYS_DATA_FROM",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "198783611"
		}, {
			"tableName": "SYS_DATA_GROUPBY",
			"tableNameCN": "SYS_DATA_GROUPBY",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "262783839"
		}, {
			"tableName": "SYS_DATA_HAVING",
			"tableNameCN": "SYS_DATA_HAVING",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "326784067"
		}, {
			"tableName": "SYS_DATA_ITEM",
			"tableNameCN": "SYS_DATA_ITEM",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1019994160"
		}, {
			"tableName": "SYS_DATA_ITEM_DEF",
			"tableNameCN": "SYS_DATA_ITEM_DEF",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "885458124"
		}, {
			"tableName": "SYS_DATA_JOIN",
			"tableNameCN": "SYS_DATA_JOIN",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "390784295"
		}, {
			"tableName": "SYS_DATA_ORDERBY",
			"tableNameCN": "SYS_DATA_ORDERBY",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "454784523"
		}, {
			"tableName": "SYS_DATA_PERMISSION",
			"tableNameCN": "SYS_DATA_PERMISSION",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1870509638"
		}, {
			"tableName": "SYS_DATA_SELECT",
			"tableNameCN": "SYS_DATA_SELECT",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "518784751"
		}, {
			"tableName": "SYS_DATA_SERVICE",
			"tableNameCN": "SYS_DATA_SERVICE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1062422304"
		}, {
			"tableName": "SYS_DATA_TABLE",
			"tableNameCN": "SYS_DATA_TABLE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "870421620"
		}, {
			"tableName": "SYS_DATA_TMPL",
			"tableNameCN": "SYS_DATA_TMPL",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "973842477"
		}, {
			"tableName": "SYS_DATA_WHERE",
			"tableNameCN": "SYS_DATA_WHERE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "582784979"
		}, {
			"tableName": "SYS_DATAACCESS",
			"tableNameCN": "SYS_DATAACCESS",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1764328795"
		}, {
			"tableName": "SYS_DATABASE",
			"tableNameCN": "SYS_DATABASE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "716253352"
		}, {
			"tableName": "SYS_DATABASE_ACCESS",
			"tableNameCN": "SYS_DATABASE_ACCESS",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "56775005"
		}, {
			"tableName": "SYS_DATASET",
			"tableNameCN": "SYS_DATASET",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "70783155"
		}, {
			"tableName": "SYS_DATASET_AUDIT",
			"tableNameCN": "SYS_DATASET_AUDIT",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "134783383"
		}, {
			"tableName": "SYS_DATASET_EXPORT",
			"tableNameCN": "SYS_DATASET_EXPORT",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1375939919"
		}, {
			"tableName": "SYS_DATASET_MAPPING",
			"tableNameCN": "SYS_DATASET_MAPPING",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "2109846524"
		}, {
			"tableName": "SYS_DATASET_MAPPING_ITEM",
			"tableNameCN": "SYS_DATASET_MAPPING_ITEM",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "26363104"
		}, {
			"tableName": "SYS_DATASET_SYNTHETIC",
			"tableNameCN": "SYS_DATASET_SYNTHETIC",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "2124414533"
		}]
	},{
		"name":"控件基础表",
		"data":[{
			"tableName": "FORM_BIMMODEL",
			"tableNameCN": "FORM_BIMMODEL",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "874366125"
		}, {
			"tableName": "FORM_BYTEARRAY",
			"tableNameCN": "FORM_BYTEARRAY",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "783469315"
		}, {
			"tableName": "FORM_COMPONENT",
			"tableNameCN": "控件信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "955993932"
		}, {
			"tableName": "FORM_COMPONENT_INSTANCE",
			"tableNameCN": "FORM_COMPONENT_INSTANCE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1083994388"
		}, {
			"tableName": "FORM_COMPONENT_PROPERTY",
			"tableNameCN": "控件属性表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1147994616"
		}, {
			"tableName": "FORM_DATASET",
			"tableNameCN": "数据集引用表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "352600240"
		}, {
			"tableName": "FORM_DATASET_RELATION",
			"tableNameCN": "数据集引用明细表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1488604287"
		}, {
			"tableName": "FORM_DESIGN_ENTITY",
			"tableNameCN": "FORM_DESIGN_ENTITY",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1247470968"
		}, {
			"tableName": "FORM_DICT_TREE",
			"tableNameCN": "控件基础字典树表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "815833814"
		}, {
			"tableName": "FORM_DICTORY",
			"tableNameCN": "控件基础字典信息",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "735833529"
		}, {
			"tableName": "FORM_EVENT",
			"tableNameCN": "事件流程表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1793321394"
		}, {
			"tableName": "FORM_EVENT_COMPLEX",
			"tableNameCN": "事件流程复合构件表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "764461743"
		}, {
			"tableName": "FORM_FILE_",
			"tableNameCN": "地图数据文件表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "947414390"
		}, {
			"tableName": "FORM_LAYOUT",
			"tableNameCN": "FORM_LAYOUT",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1039470227"
		}, {
			"tableName": "FORM_NODE_MESSAGE",
			"tableNameCN": "短信信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "653841337"
		}, {
			"tableName": "FORM_OUTEXP_RELATION",
			"tableNameCN": "控件扩展引用表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "63935245"
		}, {
			"tableName": "FORM_PAGE",
			"tableNameCN": "页面信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "371256173"
		}, {
			"tableName": "FORM_PAGE_CATEGORY",
			"tableNameCN": "页面模块",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1210315267"
		}, {
			"tableName": "FORM_PAGE_EVENT_PROCDEF",
			"tableNameCN": "FORM_PAGE_EVENT_PROCDEF",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "99307259"
		}, {
			"tableName": "FORM_PARAMS",
			"tableNameCN": "参数引用表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "320600126"
		}, {
			"tableName": "FORM_PARAMS_RELATION",
			"tableNameCN": "参数引用明细表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1520604401"
		}, {
			"tableName": "FORM_RULE",
			"tableNameCN": "页面规则表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "435256401"
		}, {
			"tableName": "FORM_RULE_PROPERTY",
			"tableNameCN": "页面规则属性明细",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "365124287"
		}, {
			"tableName": "FORM_TEMPLATE",
			"tableNameCN": "控件模板表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "79779137"
		}, {
			"tableName": "FORM_TREE",
			"tableNameCN": "FORM_TREE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "780357690"
		}, {
			"tableName": "FORM_VIDEO",
			"tableNameCN": "FORM_VIDEO",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "844357918"
		}, {
			"tableName": "FORM_WORKFLOW_PLAN",
			"tableNameCN": "FORM_WORKFLOW_PLAN",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1533792417"
		}, {
			"tableName": "FORM_WORKFLOW_RULE",
			"tableNameCN": "FORM_WORKFLOW_RULE",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1900361680"
		}]
	},{
		"name":"用户相关表",
		"data":[{
			"tableName": "USERINFO",
			"tableNameCN": "用户信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "605372671"
		},{
			"tableName": "NET_ROLE",
			"tableNameCN": "角色信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "605372671"
		},{
			"tableName": "UI_USER_THEME",
			"tableNameCN": "角色主题表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "605372671"
		},{
			"tableName": "SYS_DEPARTMENT",
			"tableNameCN": "部门信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "605372671"
		},{
			"tableName": "SYS_DEPT_ROLE",
			"tableNameCN": "部门角色表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "1729321166"
		},{
			"tableName": "SYS_DEPT_ROLE_POST",
			"tableNameCN": "sys_dept_role_post",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "850698024"
		},{
			"tableName": "SYS_PERMISSION",
			"tableNameCN": "权限信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		}]
	},{
		"name":"系统基础表",
		"data":[{
			"tableName": "SYS_TREE",
			"tableNameCN": "字典树",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_DICTORY",
			"tableNameCN": "字典信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_DBID",
			"tableNameCN": "ID生成表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_TEMPLATE",
			"tableNameCN": "页面UI模板表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_APPLICATION",
			"tableNameCN": "系统模块表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_PROPERTY",
			"tableNameCN": "系统参数表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_SCHEDULER",
			"tableNameCN": "调度信息表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_SCHEDULER_PARAMS",
			"tableNameCN": "调度参数表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		},{
			"tableName": "SYS_SCHEDULER_EXECUTION",
			"tableNameCN": "SYS_SCHEDULER_EXECUTION",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "861373583"
		}]
	},{
		"name":"测试数据",
		"data":[{
			"tableName": "FORM_RULE",
			"tableNameCN": "页面规则表",
			"biaoduan": "default",
			"tableType": "4",
			"biaoduanCn": "默认",
			"importDataRule": "2",
			"id": "435256401"
		}]
	}
]