insert into sys_tree (id, parent, name, nodedesc, sort, code, discriminator, treeid, moveable, icon, iconCls, url, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, PROVIDERCLASS) values (1720,3,'文件中心', '文件中心', 1, 'app_1720', 'A', '1|3|1720', null, null, null, null, null, 0, null );
insert into sys_tree (id, parent, name, nodedesc, sort, code, discriminator, treeid, moveable, icon, iconCls, url, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, PROVIDERCLASS) values (1721,1720,'存储设置', '存储设置', 1, 'app_1721', 'A', '1|3|1720|1721|', null, null, null, '/mx/sys/repository?showIni=true&nodeId=0', null, 0, null );
insert into sys_tree (id, parent, name, nodedesc, sort, code, discriminator, treeid, moveable, icon, iconCls, url, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, PROVIDERCLASS) values (1722,1720,'数据列表', '数据列表', 2, 'app_172451', 'A', '1|3|1720|1722|', null, null, null, '/mx/repository/data', null, 0, null );
insert into sys_tree (id, parent, name, nodedesc, sort, code, discriminator, treeid, moveable, icon, iconCls, url, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, PROVIDERCLASS) values (1723,1720,'数据处理', '数据处理', 3, 'data_parser', 'A', '1|3|1720|1723|', null, null, null, '/mx/repository/parser', null, 0, null );

insert into sys_application (ID, CODE, APPDESC, locked, NAME, NODEID, SHOWMENU, SORT, IMAGEPATH, DATABASEID_, LINKFILEID, LINKFILENAME, LINKPARAM, LINKTYPE, REFID1, REFID2, REFID3, REFID4, REFID5, REFNAME1, REFNAME2, REFNAME3, REFNAME4, REFNAME5, UID_, FLOWID_, CELLTREEDOTINDEX_, POSITION_, SYSTEMFLAG_, PAGEID_, URL) values ( 1720, 'app_1720', '文件中心', 0, '文件中心', 1720, 1, 1, null, null, null, null, null, null, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, null, null, null );
insert into sys_application (ID, CODE, APPDESC, locked, NAME, NODEID, SHOWMENU, SORT, IMAGEPATH, DATABASEID_, LINKFILEID, LINKFILENAME, LINKPARAM, LINKTYPE, REFID1, REFID2, REFID3, REFID4, REFID5, REFNAME1, REFNAME2, REFNAME3, REFNAME4, REFNAME5, UID_, FLOWID_, CELLTREEDOTINDEX_, POSITION_, SYSTEMFLAG_, PAGEID_, URL) values ( 1721, 'app_1721', '存储设置', 0, '存储设置', 1721, 1, 1, null, null, null, null, null, null, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, null, null, '/mx/sys/repository?showIni=true&nodeId=0' );
insert into sys_application (ID, CODE, APPDESC, locked, NAME, NODEID, SHOWMENU, SORT, IMAGEPATH, DATABASEID_, LINKFILEID, LINKFILENAME, LINKPARAM, LINKTYPE, REFID1, REFID2, REFID3, REFID4, REFID5, REFNAME1, REFNAME2, REFNAME3, REFNAME4, REFNAME5, UID_, FLOWID_, CELLTREEDOTINDEX_, POSITION_, SYSTEMFLAG_, PAGEID_, URL) values ( 1722, 'app_1722', '数据列表', 0, '数据列表', 1722, 1, 1, null, null, null, null, null, null, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, null, null, '/mx/repository/data' );
insert into sys_application (ID, CODE, APPDESC, locked, NAME, NODEID, SHOWMENU, SORT, IMAGEPATH, DATABASEID_, LINKFILEID, LINKFILENAME, LINKPARAM, LINKTYPE, REFID1, REFID2, REFID3, REFID4, REFID5, REFNAME1, REFNAME2, REFNAME3, REFNAME4, REFNAME5, UID_, FLOWID_, CELLTREEDOTINDEX_, POSITION_, SYSTEMFLAG_, PAGEID_, URL) values ( 1723, 'app_1723', '数据处理', 0, '数据处理', 1723, 1, 1, null, null, null, null, null, null, 0, 0, 0, 0, 0, null, null, null, null, null, null, null, null, null, null, null, '/mx/repository/parser' );
